In [1]:
import numpy as np

In [2]:
#BASIC ARRAY CREATION
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [3]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [4]:
arr3 = np.array([1,2,3,4,"hello"])
print(arr3)

['1' '2' '3' '4' 'hello']


In [5]:
# ARRAY AGENERTION FUNCTION
arr4 = np.arange(1,11)
print(arr4)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
arr5 = np.zeros(6)
print(arr5)

[0. 0. 0. 0. 0. 0.]


In [7]:
arr6 = np.zeros((3,4))
print(arr6)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
arr7 = np.ones((2,5))
print(arr7)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
# RANDOM GENERATION FUNCTION
arr8 = np.linspace(1,10,20)
print(arr8)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [10]:
arr9 = np.random.rand(3) # 0-1
print(arr9)

[0.27171237 0.02024743 0.96833772]


In [11]:
arr10 = np.random.randn(50) # -3 to 3
print(arr10)

[-1.03957772 -0.10251277  0.99410513 -1.29155599  0.60206649 -1.53857115
  2.20967177 -0.23738542  0.39583756 -0.22198921 -0.52017845  0.46622771
 -0.038151   -0.32294202 -2.00568554 -0.10216204 -2.14753522 -0.59086441
  0.26708001 -0.76028664  0.41394252  0.45078645 -0.81576839 -0.05279526
  0.33514138  0.71435663 -1.09888202  1.2933461   1.08565067 -0.30286076
 -0.3131418   1.08589996  0.92261123  1.04680446  0.15408158 -2.1730751
 -0.5023205   3.43677582 -0.50467362 -0.29713028  0.87946231 -0.06527948
 -1.49592402 -0.15566393 -1.27876343 -0.08170172 -0.11134348 -0.58214788
 -0.77658884 -0.66927981]


In [12]:
arr11 = np.random.randint(1,1000,10)
print(arr11) 

[634  43 970  52 846 786 900 184 182 597]


In [13]:
arr12 = np.eye(5)
print(arr12)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
# ARRAY ATTRIBUTES
arr13 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr13)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
arr13.shape

(3, 3)

In [16]:
arr13.size

9

In [17]:
arr13.dtype

dtype('int64')

In [18]:
# ARRAY METHODS
arr13.min()

np.int64(1)

In [19]:
arr13.max()

np.int64(9)

In [20]:
arr13.sum()

np.int64(45)

In [21]:
arr14 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr14)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
np.sum(arr14 , axis = 0)

array([12, 15, 18])

In [23]:
np.sum(arr14, axis=1)

array([ 6, 15, 24])

In [24]:
arr14.mean()

np.float64(5.0)

In [25]:
arr14.std()

np.float64(2.581988897471611)

In [26]:
arr14.argmax()

np.int64(8)

In [27]:
arr14.argmin()

np.int64(0)

In [28]:
# RESHAPING AND RESIZING
arr15 = np.arange(1,21).reshape(4,5)
print(arr15)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [29]:
# NUMPY INDEXING AND SLICING OF VECTORS
arr17 = np.arange(1,11)
print(arr17)

[ 1  2  3  4  5  6  7  8  9 10]


In [30]:
arr17[1::2]

array([ 2,  4,  6,  8, 10])

In [31]:
# NUMPY INDEXING AND SLICING OF METRIX
arr18 = np.arange(1,31).reshape(6,5)
print(arr18)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [32]:
print(arr18[0])

[1 2 3 4 5]


In [33]:
print(arr18[0,0])

1


In [34]:
print(arr18[5,4])

30


In [35]:
arr19 = np.arange(1,31).reshape(6,5)
print(arr19)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [36]:
s = arr19[3:,3:]
print(s)

[[19 20]
 [24 25]
 [29 30]]


In [37]:
s1 =arr19[0:,3]
print(s1)

[ 4  9 14 19 24 29]


In [38]:
# BOOLEAN INDEXING
arr20 = np.arange(1,21)
print(arr20)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [39]:
bool_index = arr20 % 2 == 0
print(bool_index)

[False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True]


In [40]:
b = arr20[bool_index]
print(b)

[ 2  4  6  8 10 12 14 16 18 20]


In [41]:
# ARRAY OPRATION
arr21 = np.array([1,2,3,4,5])
arr22 = np.array([6,7,8,9,10])
print(arr21)
print(arr22)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [42]:
# ARTHMETIC OPRATIONS
print(arr21+arr22)

[ 7  9 11 13 15]


In [43]:
print(arr21*arr22)

[ 6 14 24 36 50]


In [44]:
# BOADCASTING
arr23 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr23)

[ 1  2  3  4  5  6  7  8  9 10]


In [45]:
arr23 = arr23*10
print(arr23)

[ 10  20  30  40  50  60  70  80  90 100]


In [46]:
# DEEP AND SHALLOW COPY
arr24 = np.arange(1,21)
print(arr24)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [47]:
slice = arr24*10
print(slice)

[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180
 190 200]


In [48]:
print(arr24)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [49]:
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [50]:
a = b
b[0] = 99
print(b)

[99  4  6  8 10 12 14 16 18 20]


In [51]:
print(a)

[99  4  6  8 10 12 14 16 18 20]


In [52]:
a2 = np.arange(1,11)
print(a2)

[ 1  2  3  4  5  6  7  8  9 10]


In [53]:
b = a2.copy()
print(b)

[ 1  2  3  4  5  6  7  8  9 10]


In [54]:
b[0] = 99
print(b)

[99  2  3  4  5  6  7  8  9 10]


In [55]:
print(a2)

[ 1  2  3  4  5  6  7  8  9 10]


In [56]:
#MATRIX OPERATION
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [57]:
print(A @ B)

[[19 22]
 [43 50]]


In [58]:
A.T

array([[1, 3],
       [2, 4]])

In [59]:
# ADVANCE ARRAY MANIPULATION
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
print(a1)
print(a2)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [60]:
#STAKING ARRAY
np.vstack(a1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [61]:
np.vstack((a1,a2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [62]:
np.hstack((a1,a2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
np.column_stack((a1,a2))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [64]:
#SPLITTING ARRAY
ar = np.arange(1,41).reshape(10,4)
print(ar)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]
 [33 34 35 36]
 [37 38 39 40]]


In [65]:
np.hsplit(ar,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22],
        [25, 26],
        [29, 30],
        [33, 34],
        [37, 38]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24],
        [27, 28],
        [31, 32],
        [35, 36],
        [39, 40]])]

In [66]:
np.vsplit(ar,2)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]]),
 array([[21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36],
        [37, 38, 39, 40]])]

In [67]:

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [68]:
#Find the average age of students.
age = data[0:,0]
print(age)

[18 19 17 18 20]


In [69]:
avg = age.mean()
print(avg)

18.4


In [70]:
#Extract Math marks of all students.
math = data[0:,1]
print(math)

[85 92 76 65 90]


In [71]:
#Find the highest Science mark.
Science = data[0:,2]
print(Science)

[78 88 95 70 85]


In [72]:
highest_science =Science.max()
print(highest_science)

95


In [73]:
#Get details of the student who scored more than 90 in Math.
for i in range(len(data)):
     if math[i] >= 90:
        print(data[i])

[19 92 88]
[20 90 85]


In [74]:
#Increase Math marks of all students by 5.
math = data[0:,1]
print(math)

[85 92 76 65 90]


In [75]:
math+=5
print(math)

[90 97 81 70 95]


In [76]:
print(data)

[[18 90 78]
 [19 97 88]
 [17 81 95]
 [18 70 70]
 [20 95 85]]


In [77]:
print(age)

[18 19 17 18 20]


In [78]:
#Find how many students are younger than 19.
for i in range(len(data)):
    if age[i]<=19:
        print(data[i])

[18 90 78]
[19 97 88]
[17 81 95]
[18 70 70]


In [79]:
#Calculate the average marks in each subject (column-wise mean).
math_avg=data[0:,1].mean()
print(math_avg)

86.6


In [80]:
Science_avg=data[0:,2].mean()
print(Science_avg)

83.2


In [81]:
print(data)

[[18 90 78]
 [19 97 88]
 [17 81 95]
 [18 70 70]
 [20 95 85]]


In [82]:
#Get data of students who scored at least 80 in both subjects.
for i in range(len(data)):
    if math[i]>=80 and Science[i]>=80:
        print(data[i])

[19 97 88]
[17 81 95]
[20 95 85]


In [83]:
Science = data[0:,2]
print(Science)

[78 88 95 70 85]


In [84]:
#Replace all Science marks < 75 with 0.
for i in range(len(Science)):
    if Science[i]<75:
        Science[i] = 0
print(Science)

[78 88 95  0 85]


In [85]:
print(data)

[[18 90 78]
 [19 97 88]
 [17 81 95]
 [18 70  0]
 [20 95 85]]


In [86]:
#Get the shape of the matrix.
print(data.shape)

(5, 3)
